apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-springboot-app
spec:
  replicas: 3  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: moetezz/medianet:latest  # Replace with your Docker image and tag
        ports:
        - containerPort: 8080  # Port your Spring Boot application listens on
      
